CREATE TABLE IF NOT EXISTS USER_DOC_REF(
	DOC_ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL REFERENCES USERS(USER_ID),
	magic_no BIGINT NOT NULL,
	DOC_PATH VARCHAR(64),
	file_name varchar(64),
	creation_time timestamp
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;